function y = highpass_filter(x,plotResponse)
%FILTRE2 Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the DSP System Toolbox 9.0.
% Generated on: 26-Oct-2015 13:20:09

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    % The following code was used to design the filter coefficients:
    %
    % Fstop = 500;    % Stopband Frequency
    % Fpass = 2000;   % Passband Frequency
    % Astop = 80;     % Stopband Attenuation (dB)
    % Apass = 1;      % Passband Ripple (dB)
    % Fs    = 44100;  % Sampling Frequency
    %
    % h = fdesign.highpass('fst,fp,ast,ap', Fstop, Fpass, Astop, Apass, Fs);
    %
    % Hd = design(h, 'butter', ...
    %     'MatchExactly', 'stopband', ...
    %     'SystemObject', true);
    
    Hd = dsp.BiquadFilter( ...
        'Structure', 'Direct form II', ...
        'SOSMatrix', [1 -2 1 1 -1.86871322880603 0.916780844836753; 1 -2 1 1 ...
        -1.73529591486537 0.779931729740361; 1 -2 1 1 -1.6453861177051 ...
        0.687709245143259; 1 -2 1 1 -1.60050685932821 0.641675588688507], ...
        'ScaleValues', [0.946373518410696; 0.878806911151434; ...
        0.833273840712091; 0.81054561200418; 1]);
end

if (plotResponse)
    fvtool(Hd, 'Fs', 44100);
    disp('press a key to continue');
    pause;
    close(gcf);
end
y = step(Hd,x);


